prepare:
  test_size: 0.2
  val_size: 0.1
  random_state: 42
  target_col: CO(GT)
  missing_value: -200    # missing values are represented by -200 in the dataset
  co_high_threshold: 2.0 # CO threshold from which high_pollution = 1 

featurize:
  normalize: true         # normalisation min-max
  drop_na_rows: true      # supprimer les lignes trop incomplètes
  add_time_features: true # extraire heure, jour, mois depuis Date/Time

train:
  n_estimators: 100
  max_depth: 8
  min_samples_split: 4
  random_state: 42

evaluate:
  threshold: 0.80         # acceptable accuracy threshold 
